add more installation details
swinton/github-app-repl pull request #5
Opened 2019-02-21 22:26 UTC by pravipati

@swinton thanks for making this 😸. I added some documentation related to our conversation this morning.

2019-02-21 23:19 UTC, swinton requested changes
Thanks @pravipati. I can see there's some friction in setting this up, and I agree it would be good to improve it.

So that the README doesn't become out-of-date, and so that the instructions also apply to Organization-owned GitHub Apps, I think we should link to the existing documentation where possible, such as [Generating a private key](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#generating-a-private-key).

I've made a few suggestions along these lines :bow:

2019-02-21 23:19 UTC, swinton commented on README.md
> +It expects a `APP_ID` environment variable, and corresponding `.pem` file. Most Probot projects should have this.
```suggestion
```

2019-02-21 23:19 UTC, swinton commented on README.md
> +
```suggestion
```

2019-02-21 23:19 UTC, swinton commented on README.md
> +To find these details for a GitHub App you have installed, log into GitHub and from your profile view go to `Settings > Developer Settings > GitHub Apps > YOUR_APP > EDIT`
```suggestion
```

2019-02-21 23:19 UTC, swinton commented on README.md
> +From here, you can generate a new private key if you'd like. You will need either need to move the `.pem` file into `gitHub-app-repl`'s directory or update the `.env` file to include a file path to y
```suggestion
## Configuration

A couple of environment variables are required for configuration:

1. **`APP_ID`**: This should be set to the ID of your GitHub App. 
    - This is available from the settings page of your GitHub App, as `App ID`.
1. **`PRIVATE_KEY_PATH`**: This should be set to a  local filesystem path to a private key for your GitHub App. 
    - More information on generating and downloading private keys for your GitHub Apps is [available in the documentation](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#generating-a-private-key).

These environment variables can either be set directly, or via a `.env` file that follows [this example](https://github.com/swinton/github-app-repl/blob/master/.env.example).
```

2019-02-22 00:09 UTC, pravipati commented
@swinton agreed! just batched and applied your suggestions 👏

2019-02-22 16:02 UTC, swinton approved these changes
Thanks! 🚀

2019-02-22 16:02 UTC, merged